rollodex/config/routes.rb
Rails.application.routes.draw do
  root 'contacts#list'

  get 'contacts/:name' => 'contacts#detail', as: :contact

end

rollodex/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rollodex/app/controllers/contacts_controller.rb
require 'csv'

class ContactsController < ApplicationController

  before_action do
    @contacts = []
    CSV.foreach(Rails.root + "app/controllers/data.csv", headers: true) do |row|
      @contacts << row.to_hash
    end
  end

  def list
  end

  def detail
    name = params[:name]
    @contact = @contacts.find do |contact_hash|
      contact_hash["Name"].parameterize == name
    end

  end
end

rollodex/app/helpers/application_helper.rb
module ApplicationHelper
end

rollodex/app/helpers/contacts_helper.rb
module ContactsHelper
end

rollodex/app/views/contacts/detail.html.erb
<h1><%= @contact["Name"] %></h1>

<ul>
  <li><strong>Company</strong>: <%= @contact["Company"] %></li>
  <li><strong>Email</strong>: <%= @contact["Email"] %></li>
  <li><strong>Phone</strong>: <%= @contact["Phone"] %></li>
</ul>

rollodex/app/views/contacts/list.html.erb
<h1>Contacts#list</h1>

<p>You have <%= pluralize @contacts.count, "contact" %></p>


<ul>
  <% @contacts.each do |contact| %>
    <li><%= link_to contact["Name"], contact_path(name: contact["Name"].parameterize) %></li>
  <% end %>
</ul>

rollodex/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rollodex</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>