texas/config/routes.rb
Rails.application.routes.draw do

  root 'cities#index' # 'controller#action'

  get "cities/:city_name" => "cities#show", as: :city

end

texas/app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  before_action do
    @cities = ["marfa", "austin", "houston", "bryan", "fortworth"]
  end

  def index
  end

  def show
    @city = params[:city_name]
  end

end

texas/app/helpers/cities_helper.rb
module CitiesHelper
end

texas/app/views/cities/_city.html.erb
<div class="austin">

  <div class="page-header">
    <h1><%= @city.capitalize %></h1>
  </div>

  <%= image_tag "#{@city}.jpg" %>
</div>

texas/app/views/cities/austin.html.erb
<%= render partial: 'city' %>

texas/app/views/cities/index.html.erb
<div class="page-header">
  <h1>Welcome <small>cities!</small></h1>
</div>

<ul class="list-group">
  <% @cities.each do |city| %>
    <li class="list-group-item"><%= link_to city.capitalize, city_path(city_name: city) %></li>
  <% end %>
</ul>


<div class="row">

  <% @cities.each do |city| %>

    <div class="col-xs-6 col-md-3">
      <%= link_to city_path(city_name: city), class: 'thumbnail' do %>
        <%= image_tag "#{city}.jpg" %>
      <% end %>
    </div>

  <% end %>


</div>

texas/app/views/cities/show.html.erb
<%= render partial: 'city' %>

texas/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Texas</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>


  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  </head>
<body>

  <div class="container">
    <nav>
      <ul>
        <li><%= link_to 'Home', root_path %></li>
        <% @cities.each do |city| %>
          <li><%= link_to city.capitalize, city_path(city_name: city) %></li>
        <% end %>
      </ul>
    </nav>

    <%= yield %>
  </div>

</body>
</html>